workflows:
  android-release:
    name: Android Release
    environment:
      vars:
        KEYSTORE_BASE64:
          value: ""
          secure: true
        KEYSTORE_PASSWORD:
          value: ""
          secure: true
        KEY_ALIAS:
          value: ""
          secure: true
        KEY_PASSWORD:
          value: ""
          secure: true
    scripts:
      - name: Restore keystore
        script: |
          mkdir -p android
          echo "$KEYSTORE_BASE64" | base64 -d > android/keystore.jks

      - name: Create keystore properties
        script: |
          printf "storeFile=keystore.jks\nstorePassword=%s\nkeyAlias=%s\nkeyPassword=%s\n" \
            "$KEYSTORE_PASSWORD" "$KEY_ALIAS" "$KEY_PASSWORD" > android/keystore.properties

      - name: Build signed release
        script: |
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD"

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
