workflows:
  android-release:
    name: Android Release
    environment:
      vars:
        KEYSTORE_BASE64: $KEYSTORE_BASE64
        KEYSTORE_PASSWORD: $KEYSTORE_PASSWORD
        KEY_ALIAS: $KEY_ALIAS
        KEY_PASSWORD: $KEY_PASSWORD
    scripts:
      - name: Restore keystore
        script: |
          mkdir -p android
          echo "$KEYSTORE_BASE64" | base64 -d > android/keystore.jks

      - name: Build signed release
        script: |
          cd android
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=keystore.jks \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD"

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
